name: Update Jekyll Site

on:
  schedule:
    - cron: "59 23 * * *" # Corre todos os dias à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "mapt66"
          git config --global user.email "mapt@ua.pt"
     
      - name: Pull Remote Changes
        run: |
          git pull origin main # Faz um pull das alterações remotas

      - name: Run Script to Generate Posts
        run: |
          node generatePosts.js # Altere para o nome real do script
          git status

      - name: Commit Changes if Needed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Atualizar posts diários"
            git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/mapt66/mapt66.github.io.git
          else
            echo "Sem alterações para commit."
          fi
